name: Shame the signers
on:
  workflow_dispatch:
    inputs:
      comment-id:
        description: 'The comment-id of the slash command'
        required: true
      pull_request_number:
        description: 'Set to the pull request number for this command dispatch'
        required: false
      pull_request_author:
        required: false

jobs:
  dispatchCommand:
    uses: yearn/yearn-workflows/.github/workflows/shame-workflow.yml@master
    with:
      ref: ${{ github.event.inputs.ref }}
      comment-id: ${{ github.event.inputs.comment-id }}
      GITHUB_REPOSITORY: $GITHUB_REPOSITORY
      TELEGRAM_CHAT_ID: ''
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
